DROP TABLE IF EXISTS STALE_EVENT_CHECK;
DROP TABLE IF EXISTS IDEMPOTENT_EVENT_CHECK;

CREATE TABLE IF NOT EXISTS STALE_EVENT_CHECK
(
    ID VARCHAR (255) NOT NULL,
    MISSION_ID VARCHAR (255),
    EVENT_TYPE datetime DEFAULT (datetime('now','localtime'))    
);

--COMMENT ON TABLE TEST_COMPETING_CONSUMER_GROUP IS 'Table used by Core TEST to allow only one JMS Consumer at a time to be connected to the message broker';

CREATE TABLE IF NOT EXISTS IDEMPOTENT_EVENT_CHECK
(
    ID VARCHAR(255) NOT NULL,
    MISSION_ID VARCHAR (255),
    CREW_ID VARCHAR(255),
    EVENT_CODE CLOB    
    
);

ALTER TABLE STALE_EVENT_CHECK ADD CONSTRAINT "UNIQUE_MISSION" UNIQUE (MISSION_ID);
