CREATE TABLE IF NOT EXISTS EIS_COMPETING_CONSUMER_GROUP
(
    ID VARCHAR (50), --NOT NULL CONSTRAINT EIS_ROUTE_LOCK_PK PRIMARY KEY,
    HOST_IP_ADDRESS VARCHAR (255),
    LAST_ACCESSED_TIMESTAMP datetime DEFAULT (datetime('now','localtime')),
    GROUP_KEY VARCHAR (50)
);

--COMMENT ON TABLE TEST_COMPETING_CONSUMER_GROUP IS 'Table used by Core TEST to allow only one JMS Consumer at a time to be connected to the message broker';


/*
CREATE TABLE IF NOT EXISTS TEST_EVENT_INBOX_OUTBOX
(
    ID VARCHAR(50) NOT NULL CONSTRAINT TEST_COMPETING_CONSUMER_GROUP_PK PRIMARY KEY,
    EVENT_ID VARCHAR (255),
    TOPIC_QUEUE_NAME VARCHAR(255),
    TEST_EVENT CLOB,
    EVENT_TIMESTAMP TIMESTAMP,
    IS_EVENT_PROCESSED VARCHAR(50),
    IN_OUT VARCHAR(3)
    
);


Create Table IF NOT EXISTS Event (
Id VARCHAR(100) NOT NULL,
Code VARCHAR(100) NOT NULL,
Name VARCHAR(100) NOT NULL,
Description VARCHAR(1000) NULL);


*/